AWSTemplateFormatVersion: '2010-09-09'
Description: Github Release Info Notifier - Davy Jones 2017
Parameters:
  GhOrg:
    Description: The Name of the Github Org the project is associated with
    Type: String
  GhProject:
    Description: The Name of the Github project
    Type: String
  OwnerName:
    AllowedPattern: '[a-z0-9-]+'
    Description: Owner tag to use
    Type: String
  Prefix:
    AllowedPattern: '[A-Za-z0-9-]+'
    Description: Name of the Application that the pipeline is for
    Type: String
  SubscriptionEmail:
    Description: Email Address to subscribe to the SNS Topic
    Type: String
Resources:
  GithubReleasesInfoTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
      - AttributeName: published_at_epoch
        AttributeType: N
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: published_at_epoch
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TableName:
        Fn::Sub: ${Prefix}-github-release-info
      Tags:
      - Key: Owner
        Value:
          Ref: OwnerName
      - Key: Training
        Value: 'true'
    Type: AWS::DynamoDB::Table
  GithubReleasesSNSTopic:
    Properties:
      DisplayName:
        Fn::Sub: ${Prefix}-gh-release-sns
      Subscription:
      - Endpoint:
          Ref: SubscriptionEmail
        Protocol: email
    Type: AWS::SNS::Topic
  NewReleaseNotifier:
    Properties:
      CodeUri: s3://cr-davy-agileops-training/github-notifier/0414e23462bf21523c6d33b4e82ec1d0
      Environment:
        Variables:
          GH_INFO_TABLE:
            Ref: GithubReleasesInfoTable
          LOG_LEVEL: INFO
          SNS_TOPIC:
            Ref: GithubReleasesSNSTopic
      Events:
        Timer:
          Properties:
            Schedule: cron(0 8 * * ? *)
          Type: Schedule
      Handler: notifier.lambda_handler
      Policies:
      - arn:aws:iam::aws:policy/AWSLambdaExecute
      - Statement:
        - Action:
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          - dynamodb:GetItem
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListTables
          - dynamodb:Query
          - dynamodb:Scan
          - SNS:Publish
          Effect: Allow
          Resource:
          - Fn::Join:
            - ''
            - - Fn::GetAtt:
                - GithubReleasesInfoTable
                - Arn
              - '*'
          - Ref: GithubReleasesSNSTopic
        Version: '2012-10-17'
      Runtime: python2.7
      Tags:
        Owner:
          Ref: OwnerName
        Training: 'true'
      Timeout: 10
    Type: AWS::Serverless::Function
  UpdatePackerReleaseInfo:
    Properties:
      CodeUri: s3://cr-davy-agileops-training/github-notifier/0414e23462bf21523c6d33b4e82ec1d0
      Environment:
        Variables:
          GH_INFO_TABLE:
            Ref: GithubReleasesInfoTable
          LOG_LEVEL: INFO
          ORG: hashicorp
          PROJECT: packer
      Events:
        Timer:
          Properties:
            Schedule: cron(0 22 * * ? *)
          Type: Schedule
      Handler: update_info.lambda_handler
      Policies:
      - arn:aws:iam::aws:policy/AWSLambdaExecute
      - Statement:
        - Action:
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
          - dynamodb:DescribeStream
          - dynamodb:DescribeTable
          - dynamodb:GetItem
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          - dynamodb:ListTables
          - dynamodb:PutItem
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:UpdateItem
          - dynamodb:UpdateTable
          Effect: Allow
          Resource:
          - Fn::Join:
            - ''
            - - Fn::GetAtt:
                - GithubReleasesInfoTable
                - Arn
              - '*'
        Version: '2012-10-17'
      Runtime: python2.7
      Tags:
        Owner:
          Ref: OwnerName
        Training: 'true'
      Timeout: 10
    Type: AWS::Serverless::Function
  UpdateSceptreReleaseInfo:
    Properties:
      CodeUri: s3://cr-davy-agileops-training/github-notifier/0414e23462bf21523c6d33b4e82ec1d0
      Environment:
        Variables:
          GH_INFO_TABLE:
            Ref: GithubReleasesInfoTable
          LOG_LEVEL: INFO
          ORG: cloudreach
          PROJECT: sceptre
      Events:
        Timer:
          Properties:
            Schedule: cron(0 22 * * ? *)
          Type: Schedule
      Handler: update_info.lambda_handler
      Policies:
      - arn:aws:iam::aws:policy/AWSLambdaExecute
      - Statement:
        - Action:
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
          - dynamodb:DescribeStream
          - dynamodb:DescribeTable
          - dynamodb:GetItem
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          - dynamodb:ListTables
          - dynamodb:PutItem
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:UpdateItem
          - dynamodb:UpdateTable
          Effect: Allow
          Resource:
          - Fn::Join:
            - ''
            - - Fn::GetAtt:
                - GithubReleasesInfoTable
                - Arn
              - '*'
        Version: '2012-10-17'
      Runtime: python2.7
      Tags:
        Owner:
          Ref: OwnerName
        Training: 'true'
      Timeout: 10
    Type: AWS::Serverless::Function
  UpdateTerraformReleaseInfo:
    Properties:
      CodeUri: s3://cr-davy-agileops-training/github-notifier/0414e23462bf21523c6d33b4e82ec1d0
      Environment:
        Variables:
          GH_INFO_TABLE:
            Ref: GithubReleasesInfoTable
          LOG_LEVEL: INFO
          ORG:
            Ref: GhOrg
          PROJECT:
            Ref: GhProject
      Events:
        Timer:
          Properties:
            Schedule: cron(0 22 * * ? *)
          Type: Schedule
      Handler: update_info.lambda_handler
      Policies:
      - arn:aws:iam::aws:policy/AWSLambdaExecute
      - Statement:
        - Action:
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
          - dynamodb:DescribeStream
          - dynamodb:DescribeTable
          - dynamodb:GetItem
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          - dynamodb:ListTables
          - dynamodb:PutItem
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:UpdateItem
          - dynamodb:UpdateTable
          Effect: Allow
          Resource:
          - Fn::Join:
            - ''
            - - Fn::GetAtt:
                - GithubReleasesInfoTable
                - Arn
              - '*'
        Version: '2012-10-17'
      Runtime: python2.7
      Tags:
        Owner:
          Ref: OwnerName
        Training: 'true'
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
