---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Github Release Info Notifier - Davy Jones 2017'

Parameters:
  Prefix: 
    Description: Name of the Application that the pipeline is for
    Type: String
    AllowedPattern: '[A-Za-z0-9-]+'
  SubscriptionEmail:
    Description: Email Address to subscribe to the SNS Topic
    Type: String
  OwnerName:
    Description: Owner tag to use
    Type: String
    AllowedPattern: '[a-z0-9-]+'

Resources:
  ########################################################
  #---------- CREATE GITHUB RELEASE INFO TABLE ----------#
  ########################################################
  GithubReleasesInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: 'id'
          AttributeType: 'N'
        -
          AttributeName: 'published_at_epoch'
          AttributeType: 'N'
      KeySchema:
        -
          AttributeName: 'id'
          KeyType: 'HASH'
        -
          AttributeName: 'published_at_epoch'
          KeyType: 'RANGE'
      ProvisionedThroughput: 
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TableName: !Sub ${Prefix}-github-release-info
      Tags:
        -
          Key: 'Owner'
          Value: !Ref OwnerName
        - 
          Key: 'Training'
          Value: 'true'

  ############################################################
  #---------- CREATE SNS TOPIC TO KICK OFF UPDATES ----------#
  ############################################################
  GithubReleasesUpdateSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Prefix}-gh-releases-update-sns
      Subscription:
        - 
          Endpoint: !GettAtt UpdateGithubReleaseInfo.Arn
          Protocol: 'lambda'

  ###################################################################
  #---------- CREATE SNS TOPIC TO SEND SUMMARY UPDATES TO ----------#
  ###################################################################
  GithubReleasesNotifySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Prefix}-gh-releases-notify-sns
      Subscription:
        - 
          Endpoint: !Ref SubscriptionEmail
          Protocol: 'email'

  ################################################
  #---------- KICK OFF LAMBDA FUNCTION ----------#
  ################################################
  KickOff:
    Type: AWS::Serverless::Function
    Properties:
      Handler: kick_off.lambda_handler
      Runtime: python2.7
      Timeout: 10
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - SNS:Publish
              Resource:
                - !Ref GithubReleasesUpdateSNSTopic
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(0 17 * * ? *)
      Environment:
        Variables:
          LOG_LEVEL: "INFO"
          SNS_TOPIC: !Ref GithubReleasesUpdatesSNSTopic
      Tags:
        Owner: !Ref OwnerName
        Training: "true"

  ###############################################################
  #---------- UPDATE GH RELEASES INFO LAMBDA FUNCTION ----------#
  ###############################################################
  UpdateGithubReleaseInfo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update_info.lambda_handler
      Runtime: python2.7
      Timeout: 10
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:BatchGetItem
                - dynamodb:BatchWriteItem
                - dynamodb:DescribeStream
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:GetRecords
                - dynamodb:GetShardIterator
                - dynamodb:ListStreams
                - dynamodb:ListTables
                - dynamodb:PutItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:UpdateItem
                - dynamodb:UpdateTable
              Resource:
                - !Join [ "", [ !GetAtt GithubReleasesInfoTable.Arn, "*" ] ]
      Events:
        Sns:
          Type: SNS
          Properties:
            Topic: !GettAtt GithubReleasesUpdateSNSTopic
      Environment:
        Variables:
          LOG_LEVEL: "INFO"
          GH_INFO_TABLE: !Ref GithubReleasesInfoTable
      Tags:
        Owner: !Ref OwnerName
        Training: "true"

  ############################################################
  #---------- NEW RELEASE NOTIFIER LAMBDA FUNCTION ----------#
  ############################################################
  NewReleaseNotifier:
    Type: AWS::Serverless::Function
    Properties:
      Handler: notifier.lambda_handler
      Runtime: python2.7
      Timeout: 10
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:GetRecords
                - dynamodb:GetShardIterator
                - dynamodb:ListTables
                - dynamodb:Query
                - dynamodb:Scan
                - SNS:Publish
              Resource:
                - !Join [ "", [ !GetAtt GithubReleasesInfoTable.Arn, "*" ] ]
                - !Ref GithubReleasesNotifySNSTopic
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 * * ? *)
      Environment:
        Variables:
          LOG_LEVEL: "INFO"
          GH_INFO_TABLE: !Ref GithubReleasesInfoTable
          SNS_TOPIC: !Ref GithubReleasesNotifySNSTopic
      Tags:
        Owner: !Ref OwnerName
        Training: "true"
